FROM node:14.16.0-alpine as development
WORKDIR /app-ng
COPY package.json package-lock.json ./
RUN npm install
RUN npm install -g nx
ARG node_env=dev
ENV NODE_ENV $node_env
EXPOSE 4200
COPY . .

# CMD ["nx", "serve", "cbc-app-ng  --host 0.0.0.0"]
